* Work Completed
  Finally, after months of work, data is actually appearing on the screen.
  It took a lot of messing with the backend and dealing with race
  conditions, but there is finally something that you can see on the website
  other than Fishbox. All of my time for the past 2 weeks has been spent
  getting this to work, and work it does.

* Challenges
  React and Threejs interact in strange ways through React3Fiber, and
  dealing with that was very challenging. My initial Fishbox implementation
  was very flawed, and these flaws became very apparent when I began to do
  more complex rendering. First, the canvas was not being rendered in time
  for Threejs to actually draw it on the screen, so there was a race
  condition that Fishbox simply did not have. Second, I switched from using
  a regular HTML canvas as a texture and began using a DataTexture, a
  dedicated Threejs component. Of course, this came with its own challenges,
  like me not realizing that the DataTexture needs to be told to update, so
  it never rendered.

* Next Week
  The main goal for next week is to get multiple data tiles rendered at the
  same time. If that ends up not being hard, I will attempt to implement
  dynamic loading, so new tiles are generated as the user pans around.
